# Change these first
owner: itbm-services # Your GitHub organization or username, where this repository lives
repo: projects # The name of this repository

sites:
  - name: ITBM WebSite
    url: https://itbm.mx
  - name: GPTW MX
    url: https://greatplacetowork.com.mx
  - name: GPTW CARCA
    url: https://greatplacetoworkcarca.com/es
  - name: Impulso Humano
    url: https://impulsohumano.org
  - name: ULINEA
    url: http://35.202.182.224
  - name: Lucy Meza
    url: https://lucymeza.si
  - name: GCTI
    url: https://greatculturetoinnovate.org

assignees:
   - itbm-services

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /projects
  logoUrl: https://itbm.mx/wp-content/uploads/2023/02/cropped-512X512.png
  name: Status ITBM Projects
  introTitle: "**Status ITBM** is the monitor of ITBM projects"
  introMessage: This is a **real-time** view of the services. Monitor uptime every 5 minutes.
  navbar:
    - title: Status
      href: /
    - title: ITBM Projects
      href: https://itbm.mx

# Upptime also supports notifications, assigning issues, and more
# Webhook notification
#webhook:
#  url: https://chat.googleapis.com/v1/spaces/AAAASgrKXKk/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=KApOzgW0L2YvUJVIKWISX-NE4fFJN5MpHOQB_-FZZHI%3D
# See https://upptime.js.org/docs/configuration
